spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


  h2:
    console:
      path: /h2console
      enabled: true

springdoc:
  packages-to-scan: com.miniproject.miniprojectgroupthree
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html            # Swagger UI ?? => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    operations-sorter: alpha      # alpha: ??? ? ?? ??, method: HTTP Method ? ??
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

